services:
  database:
    image: postgres:13.3
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./.dev/DEV_DB_USR:/run/secrets/db_user:ro,z
      - ./.dev/DEV_DB_PWD:/run/secrets/db_password:ro,z
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro,z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db -U $$(cat /run/secrets/db_user)"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - database_net
    ports:
      - "5454:5432"

  backend:
    image: nf-vault-backend-dev:latest
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_URL: postgresql://database:5432/db
      DB_USER_FILE: /run/secrets/db_user
      DB_PASSWORD_FILE: /run/secrets/db_password
    networks:
      - database_net
    volumes:
      - ./.dev/DEV_DB_USR:/run/secrets/db_user:ro,z
      - ./.dev/DEV_DB_PWD:/run/secrets/db_password:ro,z
    ports:
      - "8080:8080"

volumes:
  db_data:

networks:
  database_net:
  web_server_net: